version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: aftas_club
    ports:
      - "3306:3306"
  aftas-frontend:
    build:
      context: ./AFTAS-frontend/aftas-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aftas_club?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
